services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./docker/mongo_db:/data/db
      - "${PWD}:/data/project"

  ingester:
    image: python:3.11-slim
    container_name: ingester
    depends_on:
      - mongodb
    working_dir: /data/project
    environment:
      MONGO_URI: "mongodb://mongodb:27017/healthcare"
    volumes:
      - "${PWD}:/data/project"
    command: >
      sh -c "
        pip install --no-cache-dir -r requirements.txt &&
        python ingestion/ingest.py validate data/healthcare_dataset.csv --report reports/pre_ingest.json &&
        python ingestion/ingest.py load data/healthcare_dataset.csv &&
        python ingestion/ingest.py postcheck
      "