FROM python:3.11-slim

WORKDIR /app

# Installer dépendances système minimales si besoin (ex: locales, tzdata)
RUN apt-get update && apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Copier requirements et installer les libs Python
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Entrée par défaut: interpréter les chaînes passées par docker compose run
ENTRYPOINT ["bash","-lc"]