version: "3.9"

volumes:
  mongo_: {}
  raw_csv: {}
  processed_csv: {}

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS:-rootpass}
    ports: ["27017:27017"]
    volumes:
      - mongo_/data/db

  ingester:
    build:
      context: .
      dockerfile: docker/Dockerfile.ingester
    container_name: ingester
    depends_on: [mongodb]
    environment:
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/healthcare}
    working_dir: /app
    volumes:
      - ./:/app:rw              # code et README
      - raw_csv:/app/raw:rw     # CSV bruts
      - processed_csv:/app/rw  # CSV nettoyés/rejets
